server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;

    location / {
        try_files $uri /index.html;
    }

    location /api/ {
        proxy_pass http://k2w7xmp6dko8xcbhf8hix66d.lab.blazz.cl;
        proxy_http_version 1.1;
        proxy_set_header Host k2w7xmp6dko8xcbhf8hix66d.lab.blazz.cl;
    }

    location /_/ {
        proxy_pass http://k2w7xmp6dko8xcbhf8hix66d.lab.blazz.cl;
        proxy_http_version 1.1;
        proxy_set_header Host k2w7xmp6dko8xcbhf8hix66d.lab.blazz.cl;
    }
}
